/* eslint-disable @next/next/no-img-element */
/* eslint-disable @next/next/link-passhref */
import { GetServerSideProps } from "next";
import Head from "next/head";
import { sanityClient, urlFor } from "../sanity";
import { Collection } from "../typings";
import { groq } from "next-sanity";
import Link from "next/link";
import Banner from "../components/Banner";
import Service from "../components/Service";
import Footer from "../components/Footer";

interface Props {
  collections: Collection[];
}

const Home = ({ collections }: Props) => {
  return (
    <div className=''>
      <Head>
        <title>NFT Drop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <h1 className='w-52 cursor-pointer text-xl font-extralight sm:w-80 mb-10 '>
        <span className='font-extrabold underline decoration-pink-600/50'>
          Yetu
        </span>{" "}
        NFT Marketplace
      </h1> */}
      <Banner />
      <Service />
      <main className=' p-10 shadow-xl  shadow-rose-400/20'>
        <h3 className='text-center font-bold text-2xl mb-3'>
          Explore the NFT Drops
        </h3>
        <div className='grid space-x-3 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4'>
          {collections.map((collection) => (
            <Link href={`/nft/${collection.slug.current}`} key={collection._id}>
              <a className='relative block bg-black group' href=''>
                <img
                  className='absolute inset-0 object-cover w-full h-full transition-opacity opacity-75  group-hover:opacity-50'
                  src={urlFor(collection.mainImage).url()}
                  alt=''
                />
                <div className='relative p-8'>
                  <p className='text-sm font-medium tracking-widest text-pink-500 uppercase'>
                    {collection.title}
                  </p>

                  <p className='text-2xl font-bold text-white'>
                    {collection.nftCollectionName}
                  </p>

                  <div className='mt-64'>
                    <div className='transition-all transform translate-y-8 opacity-0  group-hover:opacity-100 group-hover:translate-y-0'>
                      <p className='text-sm text-white'>
                        {collection.description}
                      </p>
                    </div>
                  </div>
                </div>
              </a>
            </Link>
          ))}
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const query = groq`*[_type =="collection"]{
_id,
  title,
  address,
  description,
  nftCollectionName,
  mainImage{
  asset
},
previewImage{
  asset
},
slug{
  current
},
creator->{
  _id,
  name,
  address,
  slug{
  current
}
}
}`;
  const collections = await sanityClient.fetch(query);
  return {
    props: {
      collections,
    },
  };
};
